eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8010
spring:
  sql:
    init:
      mode: always
  application:
    name: airlines
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flights_airlines
    username: postgres
    password: password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    countries-url: http://localhost:8030/api/v1/countries

management:
  tracing:
    sampling:
      probability: 1.0