eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8030
spring:
  sql:
    init:
      mode: always
  application:
    name: countries
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flights_countries
    username: postgres
    password: password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    airlines-url: http://localhost:8010/api/v1/airlines
    airports-url: http://localhost:8020/api/v1/airports

management:
  tracing:
    sampling:
      probability: 1.0
