eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: airlines
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/airlines/**

        - id: airports
          uri: http://localhost:8020
          predicates:
            - Path=/api/v1/airports/**

        - id: countries
          uri: http://localhost:8030
          predicates:
            - Path=/api/v1/countries/**

        - id: flights
          uri: http://localhost:8040
          predicates:
            - Path=/api/v1/flights/**

        - id: reservations
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/reservations/**

        - id: routes
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/flights/**

        - id: users
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/users/**


management:
  tracing:
    sampling:
      probability: 1.0